spring:
  datasource:
    # Oracle UCP 사용
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      sql-for-validate-connection: select 1 from dual
      connection-pool-name: UCPPool
      initial-pool-size: 10
      min-pool-size: 10
      max-pool-size: 50
