spring:
  # Oracle 운영 데이터베이스 설정
  datasource:
    url: jdbc:oracle:thin:@//prod-db:1521/proddb
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # Oracle UCP 사용
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      sql-for-validate-connection: select 1 from dual
      connection-pool-name: UCPPool
      initial-pool-size: 10
      min-pool-size: 10
      max-pool-size: 50
